apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: magnus-foredrag
spec:
  environments:
    - name: noproxy
      build:
        from: main
    - name: proxy
      build:
        from: main
  components:
    - name: redis
      dockerfileName: Dockerfile.redis
      secrets:
        - REDIS_PASSWORD
      ports:
        - name: redis
          port: 6379
    - name: evildtd
      src: ./evil-dtd
      publicPort: publicport2
      ports:
        - name: publicport2
          port: 8080
      environmentConfig:
        - environment: noproxy
          replicas: 0
    - name: java
      replicas: 1
      authentication:
        oauth2:
          clientId: 5e48ca1f-a2bf-4dec-b96d-bbf8ce69f9f6
          scope: openid profile email offline_access
          setXAuthRequestHeaders: true
          setAuthorizationHeader: true
          sessionStoreType: redis
          redisStore:
            connectionUrl: redis://redis:6379
      src: ./xxe-demo
      ports:
        - name: publicport
          port: 8888
      publicPort: publicport
      runAsNonRoot: true
      environmentConfig:
        - environment: proxy
          variables:
            use_proxy: "true"
    - name: http-proxy
      src: ./http-proxy
      ports:
        - name: proxyport
          port: 3128
      runAsNonRoot: true
      environmentConfig:
        - environment: noproxy
          replicas: 0